services:
  - type: web
    name: chiron-healthcare
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
